name: Publish to Web Store

on:
  push:
    branches: [ "main" ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Create env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: yarn install

    - run: yarn release-webpack
    
    - name: Browser Platform Publish
      uses: PlasmoHQ/bpp@v3
      with:
        keys: ${{ secrets.BPP_KEYS }}